ffs.tag(`link`,(self,attrs,children)=>a
({
	style:
	`
		text-decoration:none;
		color:var(--col-white-1);
		font-weight:var(--wgt-900);
	`,
	onmouseover:e=>e.target.style.color=`var(--col-red)`,
	onmouseout:e=>e.target.style.color=`var(--col-white-1)`,
	textContent:attrs.text,
	href:attrs.to
},children));